# Generated by Django 4.1.5 on 2023-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartcartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcartitem',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
