# Generated by Django 4.1.5 on 2023-02-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
