# Generated by Django 4.1.5 on 2023-02-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
    ]
