# Generated by Django 4.1.5 on 2023-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updated_a',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
